#!/bin/bash -u

PWD=$(pwd)
ln -s $PWD/ipython        ~/.config
ln -s $PWD/terminator     ~/.config
ln -s $PWD/vim/vimrc      ~/.vimrc
ln -s $PWD/vim/vim        ~/.vim
ln -s $PWD/git/gitalias   ~/.gitalias
git config --global --replace-all include.path "~/.gitalias" "~/.gitalias"


for FILE in bashrc/etc/bash.*aliases; do
  sudo ln -s $PWD/$FILE /etc/$(basename $FILE)
done
for FILE in bashrc/bash_*aliases; do
  ln -s $PWD/$FILE ~/.$(basename $FILE)
done
