set nocompatible

set hidden

" No backup/swap
set nobackup
set noswapfile

" Map
let mapleader = ","
let g:mapleader = ","
map <silent><Leader>j :bnext<CR>
map <silent><Leader>k :bprev<CR>
map <silent><Leader>p "0p
map <silent><F3> :set invpaste<CR>
set pastetoggle=<F3>
map <silent><F4> :NumberToggle<CR>
imap <silent><F4> <C-O>:NumberToggle<CR>
map <silent><F5> :EditTest<CR>
" Do not exit visual mode when shifting
vnoremap > >gv
vnoremap < <gv

" Pathogen
execute pathogen#infect()

" Airline bundle
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_min_count = 2
" Hide file encoding and smooth separators
let g:airline_section_y = ''
let g:airline_right_sep = ''
let g:airline_left_sep = ''

" NerdTree bundle
let NERDTreeIgnore = ['\.pyc$', '\.pyo$', '^__pycache__$']
map <F2> :NERDTreeToggle<CR>

" Virtualenv bundle
let g:virtualenv_directory = '.tox'

" ansible-yaml bundle
autocmd BufNewFile,BufRead *.yaml   set filetype=ansible
autocmd BufNewFile,BufRead *.yml    set filetype=ansible

" syntax
syntax on
filetype plugin indent on

" Config
set display+=lastline

" Highlight too long lines
augroup vimrc_autocmds
    autocmd!
    autocmd FileType python highlight Excess ctermbg=Black guibg=Black
    autocmd FileType python match Excess /\%80v.*/
    autocmd FileType python set nowrap
    autocmd FileType python set tabstop=4|set shiftwidth=4|set expandtab
    augroup END
