set nocompatible

set hidden

" No backup/swap
set nobackup
set noswapfile

" Map
set pastetoggle=<F3>
map <F2> :NERDTreeToggle<CR>

" Pathogen
execute pathogen#infect()

" Airline bundle
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_min_count = 2
" Hide file encoding and smooth separators
let g:airline_section_y = ''
let g:airline_right_sep = ''
let g:airline_left_sep = ''

" NerdTree bundle

" Python-mode bundle
let g:pymode_folding = 0
let g:pymode_options_colorcolumn = 0

set laststatus=2

" syntax
syntax on
filetype plugin indent on

" Highlight too long lines
augroup vimrc_autocmds
    autocmd!
    autocmd FileType python highlight Excess ctermbg=Red guibg=Red
    autocmd FileType python match Excess /\%80v.*/
    " autocmd FileType python set nowrap
    augroup END
